name: deploy for dev
on:
  push:
    branches:
      - master
      - dev
    paths:
      - '.github/workflows/**'
      - 'src/**'
      - 'Dockerfile'
      - 'docker-compose.yml'
      # - '__test__/**'
      - 'src/**'
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set ssh key # 临时设置ssh key
        run: |
          mkdir -p ~/.ssh/
          echo "${{secrets.WFP_ID_RSA}}" > ~/.ssh/id_rsa
          cat ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan "122.51.11.120" >> ~/.ssh/known_hosts
      - name: deploy #部署
        run: |
          ssh zhangyibu@122.51.11.120 "
            cd /home/zhangyibu/EightAbdominalMuscles/taro3react;
            git remote add origin https://EightAbdominalMuscles:${{secrets.WFP_PASSWORD}}@github.com/EightAbdominalMuscles/taro3react.git -b dev;
            git checkout dev;
            git pull origin dev;
            git remote remove origin;
            docker-compose build tarodemo;
            docker-componse up -d;
          "
      - name: delete ssh key #删除 ssh key
        run: rm -rf ~/.ssh/id_rsa