name: test
on:
  push:
    branches:
      - dev
    paths:
      - '.github/workflows/**'
      - '__test__/**'
      - 'src/**'
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: lint
        run: |
          npm i
          npm run lint
  test2:
    runs-on: ubuntu-latest
    steps:
      - run: touch a.txt
      - run: echo 100 > a.txt
      - run: cat a.txt